Pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'build code'
            }
        }
        stage('Test') {
            steps {
                echo 'check quality'
                echo 'check code coverage'
            }
        }
        stage('Deploy') {
            steps {
                echo 'deploy code'
            }
        }
    }
}
